config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages' => 'pages#home'
  root 'pages#home'
  get 'about' => 'pages#about', as: 'about'

  resources :signups
  get 'thanks' => 'signups#thanks', as: 'thanks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

    def new
        @signup = Signup.new
    end

    def thanks
    end

    def create
        @signup = Signup.new(signup_params)
        if @signup.save
          redirect_to thanks_path
        else
          render :new
        end
    end
    
    private
    
    def signup_params
        params.require(:signup).permit(:firstname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Stories</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500&family=Roboto:wght@100;300;400;700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="header"></div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <li class="nav-item active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_signup_path %></li>
    </ul>
  </div>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/share.jpg); height: 700px;">
    <div class="container">
        <h1>Relive your favorite memories</h1>
    </div>
</div>

<div class="container text">
    <h1 class="h1two">No more sorting through photos</h1>
    <p id="p-two" style="text-align: center">Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
    <div class="row justify-content-center">
        <%= link_to "Sign up", new_signup_path, class: "btn btn-primary" %>
    </div>
</div>

<div class="footer">
    <div class="footer-copyright">A SHUTTERBUGG PROJECT</div>
</div>

app/views/pages/home.html.erb
<div class="header"></div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <li class="nav-item active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_signup_path %></li>
    </ul>
  </div>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/storie.jpg); height: 700px;">
    <div class="container">
        <h1>Create and share Stories</h1>
        <div class="row justify-content-center">
            <a><%= link_to "Lean more", about_path, class: "btn btn-primary" %></a>
        </div>
    </div>
</div>

<div class="container text">
    <h1 class="h1two">Relive and share your adventures</h1>
    <p>Stories automatically creates a digital journal filled with only your best photos.</p>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/nature.jpg); height: 500px;">
</div>

<div class="container text">
    <h1 class="h1two">Discover Stories</h1>
    <div class="row justify-content-center">
        <a>
        <%= link_to "Lean more", about_path, class: "btn btn-primary" %>
        </a>
    </div>
</div>

<div class="footer">
    <div class="footer-copyright">A SHUTTERBUGG PROJECT</div>
</div>

app/views/signups/new.html.erb
<div class="header"></div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <li class="nav-item active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_signup_path %></li>
    </ul>
  </div>


<div class="banner1" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/contact.jpg); height: 700px;">
    <div class="container">
        <h1 class="h1two">Get the latest updates from Stories</h1>
        <div class="row justify-content-center">
            <div class="col-4">
                <%= simple_form_for @signup do |f| %>
                    <%= f.error_notification %>
                    <%= f.label 'First name' %>
                    <div class="form-inputs">
                        <%= f.input_field :firstname, class: "form-control" %>
                    </div>
                    <%= f.label 'Email' %>
                    <div class="form-inputs">
                        <%= f.input_field  :email, class: "form-control", input_html: { autocomplete: 'email' } %>
                    </div>

                    <div class="form-actions">
                        <%= f.button :submit,'Join', class: "form-control" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="footer-two">
    <div class="footer-copyright">A SHUTTERBUGG PROJECT</div>
</div>

app/views/signups/thanks.html.erb
<div class="header"></div>
  <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>
  <div id="sidebarMenu">
    <ul class="sidebarMenuInner">
      <li class="nav-item active"><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", new_signup_path %></li>
    </ul>
  </div>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(/assets/merci.jpg); height: 700px;">
    <div class="container">
        <h1 id="merci">We'll be in touch.</h1>
    </div>
</div>

<div class="footer-two">
    <div class="footer-copyright">A SHUTTERBUGG PROJECT</div>
</div>